### PR TITLE
fix: `make_formatting_params` assumes the current buffer

### LINKED ISSUE #58: messes up files when writing into multiple files at once with multiple formating lsp providers
how to reproduce:

- install sumneko lua-language-server
- install stylua
- install null-ls and enable stylua formatter
- open about 50 lua files with, e.g. `vim lua/**/*.lua`
- run `bufdo w`

vim will start writing into all those files and lsp-format will endup with file contents mixed between the files. e.g.
file `foo` will have content of file `bar`, which, in turn will have content of file `baz` etc.

### LINKED ISSUE #92: Formatting results are occasionally applied to the wrong file
When editing 2 or more different files, occasionally the formatting result from one file will be applied to the previous file instead of the current file. I think this issue is either related to, or the same as, both #58 and #71. However, unlike those 2 issues, I was able to create a mostly consistent minimal reproduction of the bug, which you can see [here](https://github.com/loganswartz/lsp-format-multi-file-formatting-bug).

I added some further notes and observations in the README of that repo, but take them with a grain of salt, as I haven't exhaustively tested those speculations. That reproduction works pretty reliably for me, but since it seems to be timing related, you may have to coerce it into working on your environment by modifying the delays.

### PR DESCRIPTION
**Pull request by lukas-reineke**
`vim.lsp.util.make_formatting_params` assumes the buffer the formatting params are generated for is the current buffer. in LSP-format this is not always the case.

fix #92
fix #58

### CODE REVIEW

File: lua/lsp-format/init.lua [hunk 1]
```diff
@@ -80,6 +80,21 @@ local parse_value = function(key, value)
...
 
+---@param bufnr number
+---@param options lsp.FormattingOptions
+---@return lsp.DocumentFormattingParams
+local function make_formatting_params(bufnr, options)
+    local tabSize = vim.api.nvim_get_option_value("shiftwidth", { buf = bufnr })
+    local expandtab = vim.api.nvim_get_option_value("expandtab", { buf = bufnr })
+    if expandtab or tabSize == 0 then
+        tabSize = vim.api.nvim_get_option_value("tabstop", { buf = bufnr })
+    end
```
Comment (liskin) [inline lua/lsp-format/init.lua:91]: Why is this logic different from the one used earlier (https://github.com/neovim/neovim/blob/e268fcbdaa1e0e0cee3b513e62581d35bb937d40/runtime/lua/vim/lsp/util.lua#L2078-L2083)? Can't we just use `get_effective_tabstop` directly?

Specifically, `vim.lsp.util.make_formatting_params` will use `sw` even if `expandtab`, but your implementation will use `tabstop` instead in such case.
